### ISSUE TITLE
Error installing "aiohttp"

### ISSUE THREAD

**Issue by jnpark3** [gnn-tracking/gnn_tracking#355]
Inside the gnn_tracking directory in my della home directory, I received the following error after running 'pip3 install -e .'

```
Collecting aiohttp; extra == "http" (from fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning[extra]->gnn-tracking==0.0.1)
  Using cached https://files.pythonhosted.org/packages/c2/fd/1ff4da09ca29d8933fda3f3514980357e25419ce5e0f689041edb8f17dab/aiohttp-3.8.4.tar.gz
    Complete output from command python setup.py egg_info:
    *********************
    * Accelerated build *
    *********************
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-voembj43/aiohttp/setup.py", line 54, in <module>
        setup(**setup_kwargs)
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 495, in parse_config_files
        ignore_option_errors=ignore_option_errors)
      File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 111, in parse_configuration
        meta.parse()
      File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 397, in parse
        section_parser_method(section_options)
      File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 370, in parse_section
        self[name] = value
      File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 174, in __setitem__
        value = parser(value)
      File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 463, in _parse_version
        version = self._parse_attr(value, self.package_dir)
      File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 320, in _parse_attr
        module = import_module(module_name)
      File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/pip-build-voembj43/aiohttp/aiohttp/__init__.py", line 5, in <module>
        from . import hdrs as hdrs
      File "/tmp/pip-build-voembj43/aiohttp/aiohttp/hdrs.py", line 8, in <module>
        from multidict import istr
    ModuleNotFoundError: No module named 'multidict'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-voembj43/aiohttp/
```

**Comment by klieret** [comment]
Hi @jnpark3 . What is the python version and what is the version if `pip3`? 

Irregardless of this, perhaps you can simply do `pip3 install --upgrade pip` and `pip3 install multidict`.

**Comment by klieret** [comment]
Was issue with old python version (3.6) because mamba env wasn't activated
