### ISSUE TITLE
Issues loading empty files from trackML dataset

### ISSUE THREAD

**Issue by klieret** [gnn-tracking/gnn_tracking#413]
```
Traceback (most recent call last):
  File "/home/kl5675/Documents/23/git_sync/gnn_tracking/src/gnn_tracking/preprocessing/build_point_clouds.py", line 72, in <module>
    pc_builder.process(start=start, stop=stop, ignore_loading_errors=False)
  File "/home/kl5675/Documents/23/git_sync/gnn_tracking/src/gnn_tracking/preprocessing/point_cloud_builder.py", line 361, in process
    hits, particles, truth, cells = load_event(
  File "/scratch/gpfs/kl5675/micromamba/envs/gnn/lib/python3.10/site-packages/trackml/dataset.py", line 110, in load_event
    return tuple(_load_event_data(prefix, name) for name in parts)
  File "/scratch/gpfs/kl5675/micromamba/envs/gnn/lib/python3.10/site-packages/trackml/dataset.py", line 110, in <genexpr>
    return tuple(_load_event_data(prefix, name) for name in parts)
  File "/scratch/gpfs/kl5675/micromamba/envs/gnn/lib/python3.10/site-packages/trackml/dataset.py", line 67, in _load_event_data
    return pandas.read_csv(files[0], header=0, index_col=False, dtype=dtype)
  File "/scratch/gpfs/kl5675/micromamba/envs/gnn/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/scratch/gpfs/kl5675/micromamba/envs/gnn/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/scratch/gpfs/kl5675/micromamba/envs/gnn/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/scratch/gpfs/kl5675/micromamba/envs/gnn/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/scratch/gpfs/kl5675/micromamba/envs/gnn/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/scratch/gpfs/kl5675/micromamba/envs/gnn/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1753, in _make_engine
    return mapping[engine](f, **self.options)
  File "/scratch/gpfs/kl5675/micromamba/envs/gnn/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 79, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 554, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

**Comment by klieret** [comment]
Let's simply ignore these
